<a href="https://colab.research.google.com/github/LEOISAIAS/Evaluaci-n/blob/main/Evaluaci%C3%B3nEtapa1_MX.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EVALUACIÓN**

ETAPA1/DATASET *MX*
## Leonardo Isaías Guevara Pioquinto

###***A01275327***

In [3]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#EUA = pd.read_csv("California_EUA.csv", encoding= 'unicode_escape')
#EUA

In [5]:
#ESP = pd.read_csv("Girona_España.csv", encoding= 'unicode_escape')
#ESP

In [ ]:
MX = pd.read_csv("DF_Mexico.csv")
MX

#***MÉXICO***

In [ ]:
#Verificamos información del DataFrame
MX.info()

In [ ]:
#Corroboramos valores nulos
valores_nulos=MX.isnull().sum()
valores_nulos

In [10]:
#Corroboramos valores nulos
valores_nulos=MX.isnull().sum()
valores_nulos.to_csv("valores_nulosMX.csv")
from google.colab import files 

files.download("valores_nulosMX.csv")

# **PROCEDIMIENTO PARA ELIMINAR VALORES NULOS EN DATAFRAME**

In [ ]:
#Reemplazamos valores nulos del dataframe con "0"
data =MX.fillna(0) 
data

Se utilizó el método de sustitución de 
valores nulos con 0 con el fin de tener mejor apreciación y manipulación de los datos, de igual forma comparar la eficacia de rellenar datos un con un valor en específico.
Reemplazar los valores nulos con ceros puede ser útil en varios escenarios. Los valores nulos pueden ser problemáticos en análisis de datos y cálculos posteriores, ya que pueden generar errores o distorsionar los resultados. Al remplazar los valores nulos con ceros, se puede facilitar el procesamiento y análisis de los datos, especialmente si los ceros son una representación razonable de la ausencia de información o una categoría distinta.
Sin embargo, es importante tener en cuenta que el reemplazo de valores nulos con ceros no siempre es la mejor estrategia. Dependerá del contexto y del significado de los valores nulos en los datos. En algunos casos, puede ser más apropiado utilizar otro valor de reemplazo o aplicar técnicas de imputación más avanzadas para estimar los valores faltantes basándose en otros datos disponibles.

In [ ]:
#Corroboramos valores nulos del dataframe
valores_nulos=MX.isnull().sum()
valores_nulos

: Esta línea de código utiliza el método isnull() de Pandas para verificar qué valores del DataFrame "MX" son nulos. Luego, se aplica el método sum() para calcular la suma de los valores nulos en cada columna del DataFrame. El resultado se asigna a una nueva variable llamada "valores_nulos".Verificar la presencia de valores nulos en un DataFrame es un paso importante en el análisis de datos. Los valores nulos pueden representar información faltante o inconsistencias en los datos, y es esencial identificarlos para poder tomar decisiones adecuadas en el procesamiento y análisis posterior.

In [ ]:
#Reemplazamos valores nulos del dataframe con "mean"
data2=MX.copy()
data2=data2.fillna(round(MX.mean(),1))
data2

Esta línea de código crea una copia del DataFrame "MX" y la asigna a una nueva variable llamada "data2". Esto se hace para evitar modificar el DataFrame original y para trabajar con una copia independiente.

data2 = data2.fillna(round(MX.mean(),1)): Esta línea de código utiliza el método fillna() de Pandas para reemplazar los valores nulos del DataFrame "data2" con la media de cada columna, redondeada a un decimal. Para ello, se utiliza el método mean() de Pandas para calcular la media de cada columna del DataFrame "MX". Luego, se utiliza la función round() para redondear el valor de la media a un decimal. Finalmente, se asigna el resultado a la variable "data2".
Reemplazar los valores nulos con la media de cada columna es una estrategia común en el procesamiento de datos. Esta estrategia ayuda a mantener la distribución de los datos y puede mejorar la precisión de los análisis posteriores.

In [ ]:
#Corroboramos valores nulos del dataframe
valores_nulos=data2.isnull().sum()
valores_nulos

In [ ]:
#Realizamos diagrama de caja o bigote de cada columna del dataframe
fig = plt.figure(figsize =(15, 8))
data2.plot(kind='box', vert=False)
plt.title("Valores Atípicos del Dataframe")
plt.show() #dibujamos el diagrama

# **PROCEDIMIENTO "DESVIACIÓN ESTÁNDAR" PARA ELIMINAR OUTLIERS EN DATAFRAME**

In [16]:
#Método aplicando desviación estandar. Encuentro los valores extremos
y=data2
Limite_Superior= y.mean() + 3*y.std()
Limite_Inferior= y.mean() - 3*y.std()
print("Limite superior permitido", Limite_Superior)
print("Limite inferior permitido", Limite_Inferior)

<ipython-input-16-4c899ed993c2>:3: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Superior= y.mean() + 3*y.std()
<ipython-input-16-4c899ed993c2>:3: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Superior= y.mean() + 3*y.std()
<ipython-input-16-4c899ed993c2>:4: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Inferior= y.mean() - 3*y.std()

Limite superior permitido id                                              1.329210e+18
scrape_id                                       2.023033e+13
host_id                                         6.520127e+08
host_listings_count                             2.528303e+02
host_total_listings_count                       4.262030e+02
neighbourhood_group_cleansed                             NaN
latitude                                        1.953257e+01
longitude                                      -9.906563e+01
accommodates                                    9.933140e+00
bathrooms                                                NaN
bedrooms                                        4.972702e+00
beds                                            6.934289e+00
minimum_nights                                  8.491454e+01
maximum_nights                                  2.018372e+03
minimum_minimum_nights                          7.457055e+01
maximum_minimum_nights                          7.564005e+01
minimum_maximum_nights                          2.164892e+03
maximum_maximum_nights                          2.164344e+03
minimum_nights_avg_ntm                          7.489017e+01
maximum_nights_avg_ntm                          2.159176e+03
calendar_updated                                         NaN
availability_30                                 4.982418e+01
availability_60                                 1.013274e+02
availability_90                                 1.522572e+02
availability_365                                6.173025e+02
number_of_reviews                               2.261108e+02
number_of_reviews_ltm                           7.424966e+01
number_of_reviews_l30d                          6.890766e+00
review_scores_rating                            6.154024e+00
review_scores_accuracy                          6.021934e+00
review_scores_cleanliness                       5.994457e+00
review_scores_checkin                           5.956907e+00
review_scores_communication                     5.996082e+00
review_scores_location                          5.883035e+00
review_scores_value                             5.984107e+00
license                                                  NaN
calculated_host_listings_count                  1.091657e+02
calculated_host_listings_count_entire_homes     1.022059e+02
calculated_host_listings_count_private_rooms    1.937095e+01
calculated_host_listings_count_shared_rooms     7.991190e+00
reviews_per_month                               6.966878e+00
dtype: float64
Limite inferior permitido id                                             -7.910303e+17
scrape_id                                       2.023033e+13
host_id                                        -2.834528e+08
host_listings_count                            -2.096972e+02
host_total_listings_count                      -3.716542e+02
neighbourhood_group_cleansed                             NaN
latitude                                        1.927322e+01
longitude                                      -9.927032e+01
accommodates                                   -3.366099e+00
bathrooms                                                NaN
bedrooms                                       -1.862398e+00
beds                                           -3.010825e+00
minimum_nights                                 -7.563730e+01
maximum_nights                                 -7.702790e+02
minimum_minimum_nights                         -6.576140e+01
maximum_minimum_nights                         -6.618515e+01
minimum_maximum_nights                         -4.655342e+02
maximum_maximum_nights                         -4.395386e+02
minimum_nights_avg_ntm                         -6.580753e+01
maximum_nights_avg_ntm                         -4.433172e+02
calendar_updated                                         NaN
availability_30                                -1.856452e+01
availability_60                                -2.683859e+01
availability_90                                -3.019081e+01
availability_365                               -1.261149e+02
number_of_reviews                              -1.529404e+02
number_of_reviews_ltm                          -4.740570e+01
number_of_reviews_l30d                         -4.643242e+00
review_scores_rating                            3.276213e+00
review_scores_accuracy                          3.540038e+00
review_scores_cleanliness                       3.484257e+00
review_scores_checkin                           3.689178e+00
review_scores_communication                     3.630301e+00
review_scores_location                          3.772378e+00
review_scores_value                             3.430624e+00
license                                                  NaN
calculated_host_listings_count                 -8.333515e+01
calculated_host_listings_count_entire_homes    -8.176727e+01
calculated_host_listings_count_private_rooms   -1.454227e+01
calculated_host_listings_count_shared_rooms    -7.536434e+00
reviews_per_month                              -3.562731e+00
dtype: float64

<ipython-input-16-4c899ed993c2>:4: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  Limite_Inferior= y.mean() - 3*y.std()

El código proporcionado tiene como objetivo calcular los límites superiores e inferiores permitidos utilizando la desviación estándar en el DataFrame "data2"

In [17]:
#Encontramos Ouliers del Dataframe
outliers= data2[(y>Limite_Superior)|(y<Limite_Inferior)]
outliers

<ipython-input-17-b3686d19c4d6>:2: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  outliers= data2[(y>Limite_Superior)|(y<Limite_Inferior)]

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24221,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24223,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
#Obtenemos datos y los outliers se convierten en nulos en el DataFrame
data3= data2[(y<=Limite_Superior)&(y>=Limite_Inferior)]
data3

<ipython-input-18-1e038dbc0c4a>:2: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  data3= data2[(y<=Limite_Superior)&(y>=Limite_Inferior)]

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2056638,NaN,20230329041210,NaN,NaN,NaN,NaN,NaN,NaN,10531228,...,4.95,5.00,4.86,NaN,NaN,3.0,3.0,0.0,0.0,0.19
1,2072354,NaN,20230329041210,NaN,NaN,NaN,NaN,NaN,NaN,16840050,...,5.00,4.95,4.84,NaN,NaN,2.0,2.0,0.0,0.0,0.54
2,696037,NaN,20230329041210,NaN,NaN,NaN,NaN,NaN,NaN,3531879,...,4.92,4.58,4.71,NaN,NaN,3.0,3.0,0.0,0.0,0.31
3,35797,NaN,20230329041210,NaN,NaN,NaN,NaN,NaN,NaN,153786,...,4.80,4.80,4.70,NaN,NaN,1.0,1.0,0.0,0.0,1.70
4,44616,NaN,20230329041210,NaN,NaN,NaN,NaN,NaN,NaN,196253,...,4.78,4.98,4.48,NaN,NaN,12.0,3.0,2.0,0.0,0.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,853923589855678923,NaN,20230329041210,NaN,NaN,NaN,NaN,NaN,NaN,488030249,...,4.80,4.80,4.70,NaN,NaN,2.0,2.0,0.0,0.0,1.70
24220,853966732274073000,NaN,20230329041210,NaN,NaN,NaN,NaN,NaN,NaN,506816029,...,4.80,4.80,4.70,NaN,NaN,1.0,1.0,0.0,0.0,1.70
24221,854225071295768399,NaN,20230329041210,NaN,NaN,NaN,NaN,NaN,NaN,154670560,...,4.80,4.80,4.70,NaN,NaN,1.0,0.0,1.0,0.0,1.70
24222,854247693069190865,NaN,20230329041210,NaN,NaN,NaN,NaN,NaN,NaN,7799414,...,4.80,4.80,4.70,NaN,NaN,13.0,13.0,0.0,0.0,1.70
24223,854260329845513725,NaN,20230329041210,NaN,NaN,NaN,NaN,NaN,NaN,506864314,...,4.80,4.80,4.70,NaN,NaN,2.0,2.0,0.0,0.0,1.70

In [19]:
#Eliminamos columnas innecesarias
data= data.drop(['neighbourhood_group_cleansed', 'bathrooms', 'calendar_updated'], axis=1)
data

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2056638,https://www.airbnb.com/rooms/2056638,20230329041210,2023-03-30,city scrape,Amplio y luminoso loft en Coyoacán,Cómodo loft de dos pisos magníficamente ubicad...,0,https://a0.muscache.com/pictures/28353712/4379...,10531228,...,4.95,5.00,4.86,0.0,f,3,3,0,0,0.19
1,2072354,https://www.airbnb.com/rooms/2072354,20230329041210,2023-03-30,city scrape,Coyoacan Historic Studio Apartment,This studio flat is adjacent to the owner's ho...,"Located in Coyoacan, in a quiet neighborhood w...",https://a0.muscache.com/pictures/369f3371-593a...,16840050,...,5.00,4.95,4.84,0.0,f,2,2,0,0,0.54
2,696037,https://www.airbnb.com/rooms/696037,20230329041210,2023-03-29,city scrape,"3 Bedrooms, 2 blocks from Polanco - ALL RENOVA...","Beautifully decorated 3 bedroom apartment, it ...","This area is called Nuevo Polanco, it has bein...",https://a0.muscache.com/pictures/10960397/67b2...,3531879,...,4.92,4.58,4.71,0.0,f,3,3,0,0,0.31
3,35797,https://www.airbnb.com/rooms/35797,20230329041210,2023-03-29,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Centro comercial Santa Fe, parque interlomas y...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,0.00,0.00,0.00,0.0,f,1,1,0,0,0.00
4,44616,https://www.airbnb.com/rooms/44616,20230329041210,2023-03-30,city scrape,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,0,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.48,0.0,f,12,3,2,0,0.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,853923589855678923,https://www.airbnb.com/rooms/853923589855678923,20230329041210,2023-03-30,city scrape,Rincón Mexico lindo!,Este lugar tiene una ubicación estratégica: ll...,0,https://a0.muscache.com/pictures/miso/Hosting-...,488030249,...,0.00,0.00,0.00,0.0,f,2,2,0,0,0.00
24220,853966732274073000,https://www.airbnb.com/rooms/853966732274073000,20230329041210,2023-03-29,city scrape,Departamento en zona diamante.,"Ubicado en zona diamante, junto al aeropuerto,...",0,https://a0.muscache.com/pictures/miso/Hosting-...,506816029,...,0.00,0.00,0.00,0.0,t,1,1,0,0,0.00
24221,854225071295768399,https://www.airbnb.com/rooms/854225071295768399,20230329041210,2023-03-29,city scrape,Habitación privada en magnífica casa,Relájate en este espacio muy tranquilo y elega...,0,https://a0.muscache.com/pictures/db71951a-8696...,154670560,...,0.00,0.00,0.00,0.0,f,1,0,1,0,0.00
24222,854247693069190865,https://www.airbnb.com/rooms/854247693069190865,20230329041210,2023-03-30,city scrape,Espacioso y luminoso loft - Roma,What else does it come with?<br />- WIFI 100MB...,0,https://a0.muscache.com/pictures/miso/Hosting-...,7799414,...,0.00,0.00,0.00,0.0,t,13,13,0,0,0.00
24223,854260329845513725,https://www.airbnb.com/rooms/854260329845513725,20230329041210,2023-03-30,city scrape,Maravilloso departamento en Ciudad de México,Ven a descubrir este increíble departamento en...,Una zona muy bonita ya que varias de las atrac...,https://a0.muscache.com/pictures/miso/Hosting-...,506864314,...,0.00,0.00,0.00,0.0,t,2,2,0,0,0.00

In [20]:
#Corroboramos valores nulos del dataframe4
valores_nulos=data.isnull().sum()
valores_nulos

id                                              0
listing_url                                     0
scrape_id                                       0
last_scraped                                    0
source                                          0
                                               ..
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
Length: 72, dtype: int64

In [21]:
#Reemplazamos valores nulos del dataframe con "0"
data_clean =data.fillna(0) 
data_clean

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,2056638,https://www.airbnb.com/rooms/2056638,20230329041210,2023-03-30,city scrape,Amplio y luminoso loft en Coyoacán,Cómodo loft de dos pisos magníficamente ubicad...,0,https://a0.muscache.com/pictures/28353712/4379...,10531228,...,4.95,5.00,4.86,0.0,f,3,3,0,0,0.19
1,2072354,https://www.airbnb.com/rooms/2072354,20230329041210,2023-03-30,city scrape,Coyoacan Historic Studio Apartment,This studio flat is adjacent to the owner's ho...,"Located in Coyoacan, in a quiet neighborhood w...",https://a0.muscache.com/pictures/369f3371-593a...,16840050,...,5.00,4.95,4.84,0.0,f,2,2,0,0,0.54
2,696037,https://www.airbnb.com/rooms/696037,20230329041210,2023-03-29,city scrape,"3 Bedrooms, 2 blocks from Polanco - ALL RENOVA...","Beautifully decorated 3 bedroom apartment, it ...","This area is called Nuevo Polanco, it has bein...",https://a0.muscache.com/pictures/10960397/67b2...,3531879,...,4.92,4.58,4.71,0.0,f,3,3,0,0,0.31
3,35797,https://www.airbnb.com/rooms/35797,20230329041210,2023-03-29,city scrape,Villa Dante,"Dentro de Villa un estudio de arte con futon, ...","Centro comercial Santa Fe, parque interlomas y...",https://a0.muscache.com/pictures/f395ab78-1185...,153786,...,0.00,0.00,0.00,0.0,f,1,1,0,0,0.00
4,44616,https://www.airbnb.com/rooms/44616,20230329041210,2023-03-30,city scrape,CONDESA HAUS B&B,A new concept of hosting in mexico through a b...,0,https://a0.muscache.com/pictures/251410/ec75fe...,196253,...,4.78,4.98,4.48,0.0,f,12,3,2,0,0.46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24219,853923589855678923,https://www.airbnb.com/rooms/853923589855678923,20230329041210,2023-03-30,city scrape,Rincón Mexico lindo!,Este lugar tiene una ubicación estratégica: ll...,0,https://a0.muscache.com/pictures/miso/Hosting-...,488030249,...,0.00,0.00,0.00,0.0,f,2,2,0,0,0.00
24220,853966732274073000,https://www.airbnb.com/rooms/853966732274073000,20230329041210,2023-03-29,city scrape,Departamento en zona diamante.,"Ubicado en zona diamante, junto al aeropuerto,...",0,https://a0.muscache.com/pictures/miso/Hosting-...,506816029,...,0.00,0.00,0.00,0.0,t,1,1,0,0,0.00
24221,854225071295768399,https://www.airbnb.com/rooms/854225071295768399,20230329041210,2023-03-29,city scrape,Habitación privada en magnífica casa,Relájate en este espacio muy tranquilo y elega...,0,https://a0.muscache.com/pictures/db71951a-8696...,154670560,...,0.00,0.00,0.00,0.0,f,1,0,1,0,0.00
24222,854247693069190865,https://www.airbnb.com/rooms/854247693069190865,20230329041210,2023-03-30,city scrape,Espacioso y luminoso loft - Roma,What else does it come with?<br />- WIFI 100MB...,0,https://a0.muscache.com/pictures/miso/Hosting-...,7799414,...,0.00,0.00,0.00,0.0,t,13,13,0,0,0.00
24223,854260329845513725,https://www.airbnb.com/rooms/854260329845513725,20230329041210,2023-03-30,city scrape,Maravilloso departamento en Ciudad de México,Ven a descubrir este increíble departamento en...,Una zona muy bonita ya que varias de las atrac...,https://a0.muscache.com/pictures/miso/Hosting-...,506864314,...,0.00,0.00,0.00,0.0,t,2,2,0,0,0.00

In [22]:
#Corroboramos valores nulos del dataframe LIMPIO
valores_nulos=data_clean.isnull().sum()
valores_nulos

id                                              0
listing_url                                     0
scrape_id                                       0
last_scraped                                    0
source                                          0
                                               ..
calculated_host_listings_count                  0
calculated_host_listings_count_entire_homes     0
calculated_host_listings_count_private_rooms    0
calculated_host_listings_count_shared_rooms     0
reviews_per_month                               0
Length: 72, dtype: int64

In [23]:
#Convertir DataFrame a CSV
data_clean.to_csv("Datos_limpios_MX.csv")
#descargar archivo filtrado en csv
from google.colab import files 
  
  
files.download("Datos_limpios_MX.csv")